server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kalah
    username: kalah
    password: kalah

springdoc:
  packages-to-scan: org.mrsash.kalah.controller

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /v1/actuator