server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kalah
    username: kalah
    password: kalah

springdoc:
  packages-to-scan: org.mrsash.kalahapi.controller
